// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Product struct {
	ID                 string    `json:"id"`
	ProductName        string    `json:"product_name"`
	ProductDescription string    `json:"product_description"`
	Price              float64   `json:"price"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"createdAt"`
}

type Query struct {
}
