// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Product struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	IsActive    bool   `json:"isActive"`
}

type ProductConnection struct {
	Products []*Product `json:"products"`
	Total    int        `json:"total"`
}

type ProductFilter struct {
	ID          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	MinPrice    *int64  `json:"minPrice,omitempty"`
	MaxPrice    *int64  `json:"maxPrice,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type Query struct {
}
