// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type Product struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
}

type ProductListResponse struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
}

type Query struct {
}
