package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"go-graphql/internal/graph/generated"
	"go-graphql/internal/graph/model"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, filter *model.ProductFilter, pagination *model.PaginationInput) (*model.ProductConnection, error) {
	products, err := r.ProductService.ListProducts(ctx, filter, pagination)
	if err != nil {
		return nil, fmt.Errorf("failed to list products: %w", err)
	}

	// Map service DTOs into GraphQL models
	var result []*model.Product
	for _, p := range products.Products {
		result = append(result, &model.Product{
			ID:          int(p.ID),
			Name:        p.Name,
			Description: p.Description,
			Price:       p.Price,
			IsActive:    p.IsActive,
		})
	}

	return &model.ProductConnection{
		Products: result,
		Total:    products.Total,
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
