package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"go-graphql/internal/graph/generated"
	"go-graphql/internal/graph/model"
)

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id int) (*model.Product, error) {
	product, err := r.ProductService.GetProductByID(ctx, int32(id))
	if err != nil {
		return nil, fmt.Errorf("failed to get product: %w", err)
	}

	return &model.Product{
		ID:          int(product.ID),
		Name:        product.Name,
		Description: product.Description,
		Price:       product.Price,
	}, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.ProductService.ListProducts(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list products: %w", err)
	}

	// Map service DTOs into GraphQL models
	var result []*model.Product
	for _, p := range products {
		result = append(result, &model.Product{
			ID:          int(p.ID),
			Name:        p.Name,
			Description: p.Description,
			Price:       p.Price,
		})
	}

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
